Repository CS2103-AY1819S1-W14-1/main, pull requests merged in 2018-11, with the labels that each got.

#176 Update dev guide
  docs/DeveloperGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#172 Update Project Portfolio Page
  docs/DeveloperGuide.adoc
  docs/team/jjlee050.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#174 Update User Guide
  docs/UserGuide.adoc
  docs/images/user-guide-login-after.png
  docs/images/user-guide-login-before.png
  docs/images/user-guide-ui-walkthrough-overview.png
Labels: PRStatus.ReadyForReview, role.Documentation

#155 Assign patient to the queue.
  src/main/java/seedu/clinicio/logic/Logic.java
  src/main/java/seedu/clinicio/logic/LogicManager.java
  src/main/java/seedu/clinicio/logic/commands/AddCommand.java
  src/main/java/seedu/clinicio/logic/commands/DequeueCommand.java
  src/main/java/seedu/clinicio/logic/commands/EditCommand.java
  src/main/java/seedu/clinicio/logic/commands/EnqueueCommand.java
  src/main/java/seedu/clinicio/logic/commands/ShowPatientInQueueCommand.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/logic/parser/DequeueCommandParser.java
  src/main/java/seedu/clinicio/logic/parser/EditCommandParser.java
  src/main/java/seedu/clinicio/logic/parser/EnqueueCommandParser.java
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/Model.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/patient/Patient.java
  src/main/java/seedu/clinicio/model/patientqueue/MainQueue.java
  src/main/java/seedu/clinicio/model/patientqueue/PatientQueue.java
  src/main/java/seedu/clinicio/model/person/Person.java
  src/main/java/seedu/clinicio/model/person/UniquePersonList.java
  src/main/java/seedu/clinicio/model/util/PatientComparator.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedPatient.java
  src/main/java/seedu/clinicio/storage/XmlSerializableClinicIo.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/test/java/seedu/clinicio/logic/commands/AddCommandTest.java
  src/test/java/seedu/clinicio/model/patientqueue/MainQueueTest.java
  src/test/java/seedu/clinicio/storage/XmlSerializableClinicIoTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: PRStatus.ReadyForReview, charge.Logic, charge.Model

#185 Edit examples for login
  docs/UserGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#190 Fix bugs found in PE with regards to login
  src/main/java/seedu/clinicio/logic/commands/LoginCommand.java
  src/main/java/seedu/clinicio/logic/parser/ParserUtil.java
  src/main/java/seedu/clinicio/model/staff/Password.java
Labels: PRStatus.WIP, charge.Logic, charge.Model, role.CodeQuality, role.Testing

#191 Update ClinicIoParser.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
Labels: PRStatus.ReadyForReview, charge.Logic

#224 Fix login bugs found in PE dry run
  src/main/java/seedu/clinicio/commons/core/UserSession.java
  src/main/java/seedu/clinicio/commons/events/ui/LoginSuccessEvent.java
  src/main/java/seedu/clinicio/commons/events/ui/NewResultAvailableEvent.java
  src/main/java/seedu/clinicio/ui/CommandBox.java
  src/main/java/seedu/clinicio/ui/ResultDisplay.java
  src/main/java/seedu/clinicio/ui/StatusBarFooter.java
  src/main/java/seedu/clinicio/ui/util/PasswordPrefixFormatter.java
  src/test/java/seedu/clinicio/ui/ResultDisplayTest.java
Labels: PRStatus.ReadyForReview, charge.UI, role.CodeQuality

#173 Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/LoginSequenceDiagram.png
Labels: PRStatus.ReadyForReview, role.Documentation

#189 fix #187
  src/main/java/seedu/clinicio/model/appointment/Date.java
  src/test/java/seedu/clinicio/model/appointment/DateTest.java
Labels: PRStatus.ReadyForReview, role.Testing, severity.Medium, type.Bug

#230 DeveloperGuide.adoc: Fix bug
  docs/DeveloperGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#179 Implement ListAppt and CancelAppt
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/gingivitiss.adoc
  src/main/java/seedu/clinicio/commons/core/Messages.java
  src/main/java/seedu/clinicio/commons/events/ui/AppointmentPanelSelectionChangedEvent.java
  src/main/java/seedu/clinicio/logic/Logic.java
  src/main/java/seedu/clinicio/logic/LogicManager.java
  src/main/java/seedu/clinicio/logic/commands/CancelApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListApptCommand.java
  src/main/java/seedu/clinicio/logic/parser/CancelApptCommandParser.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/logic/parser/ListApptCommandParser.java
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/appointment/AppointmentContainsDatePredicate.java
  src/main/java/seedu/clinicio/model/appointment/Date.java
  src/main/java/seedu/clinicio/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/clinicio/storage/XmlSerializableClinicIo.java
  src/main/java/seedu/clinicio/ui/AppointmentCard.java
  src/main/java/seedu/clinicio/ui/AppointmentListPanel.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/AppointmentListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/clinicio/model/ClinicIoTest.java
  src/test/java/seedu/clinicio/model/ModelManagerTest.java
  src/test/java/seedu/clinicio/model/appointment/AppointmentContainsDatePredicateTest.java
  src/test/java/seedu/clinicio/model/appointment/AppointmentTest.java
  src/test/java/seedu/clinicio/model/appointment/DateTest.java
  src/test/java/seedu/clinicio/model/appointment/TimeTest.java
  src/test/java/seedu/clinicio/model/appointment/UniqueAppointmentListTest.java
Labels: PRStatus.ReadyForReview, charge.Logic, charge.Model, charge.Storage, charge.UI

#167 Implement Logout Command
  src/main/java/seedu/clinicio/commons/events/ui/LogoutClinicIoEvent.java
  src/main/java/seedu/clinicio/logic/commands/LogoutCommand.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/ui/StatusBarFooter.java
Labels: PRStatus.ReadyForReview, charge.Logic, charge.UI

#235 Fix build errors.
  src/main/java/seedu/clinicio/ui/StatusBarFooter.java
Labels: PRStatus.ReadyForReview, type.Bug

#234 Replace dummy lists of patients
  src/main/java/seedu/clinicio/model/ExportPatientsData.java
  src/main/java/seedu/clinicio/model/ModelManager.java
Labels: PRStatus.ReadyForReview, charge.Model, priority.High

#238 Improve test coverage for ClinicIO
  build.gradle
  src/main/java/seedu/clinicio/MainApp.java
  src/main/java/seedu/clinicio/commons/core/UserSession.java
  src/main/java/seedu/clinicio/logic/commands/AddPatientCommand.java
  src/main/java/seedu/clinicio/logic/commands/CancelApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/DequeueCommand.java
  src/main/java/seedu/clinicio/logic/commands/EditCommand.java
  src/main/java/seedu/clinicio/logic/commands/EnqueueCommand.java
  src/main/java/seedu/clinicio/logic/commands/LoginCommand.java
  src/main/java/seedu/clinicio/logic/commands/MedicineStatisticsCommand.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/logic/parser/ParserUtil.java
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/patient/Nric.java
  src/main/java/seedu/clinicio/model/patient/Patient.java
  src/main/java/seedu/clinicio/model/patient/UniquePatientList.java
  src/main/java/seedu/clinicio/model/patient/exceptions/PatientNotFoundException.java
  src/main/java/seedu/clinicio/model/util/SampleDataUtil.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedPatient.java
  src/main/java/seedu/clinicio/storage/XmlSerializableClinicIo.java
  src/main/java/seedu/clinicio/ui/StatusBarFooter.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AppointmentStatisticsCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/CommandTestUtil.java
  src/test/java/seedu/clinicio/logic/commands/DoctorStatisticsCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/EditCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/LoginCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/PatientStatisticsCommandTest.java
  src/test/java/seedu/clinicio/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/clinicio/logic/parser/AddPatientCommandParserTest.java
  src/test/java/seedu/clinicio/logic/parser/CancelApptCommandParserTest.java
  src/test/java/seedu/clinicio/logic/parser/ClinicIoParserTest.java
  src/test/java/seedu/clinicio/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/clinicio/model/ClinicIoTest.java
  src/test/java/seedu/clinicio/model/ModelManagerTest.java
  src/test/java/seedu/clinicio/model/appointment/AppointmentTest.java
  src/test/java/seedu/clinicio/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/clinicio/model/consultation/UniqueConsultationListTest.java
  src/test/java/seedu/clinicio/model/patient/AllergyTest.java
  src/test/java/seedu/clinicio/model/patient/MedicalProblemTest.java
  src/test/java/seedu/clinicio/model/patient/MedicationTest.java
  src/test/java/seedu/clinicio/model/patient/NricTest.java
  src/test/java/seedu/clinicio/model/patient/PatientTest.java
  src/test/java/seedu/clinicio/model/patient/UniquePatientListTest.java
  src/test/java/seedu/clinicio/model/patientqueue/MainQueueTest.java
  src/test/java/seedu/clinicio/model/staff/PasswordTest.java
  src/test/java/seedu/clinicio/model/staff/StaffTest.java
  src/test/java/seedu/clinicio/model/staff/StaffTest.java~upstream_master
  src/test/java/seedu/clinicio/model/staff/UniqueStaffListTest.java
  src/test/java/seedu/clinicio/storage/XmlAdaptedStaffTest.java
  src/test/java/seedu/clinicio/testutil/AppointmentBuilder.java
  src/test/java/seedu/clinicio/testutil/PatientBuilder.java
  src/test/java/seedu/clinicio/testutil/TypicalPersons.java
  src/test/java/seedu/clinicio/ui/StatusBarFooterTest.java
Labels: PRStatus.ReadyForReview, role.Testing

#237 Medicine (model&storage)
  src/main/java/seedu/clinicio/logic/parser/CliSyntax.java
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/Model.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/ReadOnlyClinicIo.java
  src/main/java/seedu/clinicio/model/medicine/Medicine.java
  src/main/java/seedu/clinicio/model/medicine/MedicineDosage.java
  src/main/java/seedu/clinicio/model/medicine/MedicineName.java
  src/main/java/seedu/clinicio/model/medicine/MedicineNameContainsKeywordsPredicate.java
  src/main/java/seedu/clinicio/model/medicine/MedicinePrice.java
  src/main/java/seedu/clinicio/model/medicine/MedicineQuantity.java
  src/main/java/seedu/clinicio/model/medicine/MedicineType.java
  src/main/java/seedu/clinicio/model/medicine/UniqueMedicineList.java
  src/main/java/seedu/clinicio/model/medicine/exceptions/DuplicateMedicineException.java
  src/main/java/seedu/clinicio/model/medicine/exceptions/MedicineNotFoundException.java
  src/main/java/seedu/clinicio/model/util/SampleDataUtil.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedMedicine.java
  src/main/java/seedu/clinicio/storage/XmlSerializableClinicIo.java
  src/test/java/seedu/clinicio/logic/commands/AddCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/CommandTestUtil.java
  src/test/java/seedu/clinicio/model/ClinicIoTest.java
  src/test/java/seedu/clinicio/model/ModelManagerTest.java
  src/test/java/seedu/clinicio/model/medicine/MedicineDosageTest.java
  src/test/java/seedu/clinicio/model/medicine/MedicineNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/clinicio/model/medicine/MedicineNameTest.java
  src/test/java/seedu/clinicio/model/medicine/MedicinePriceTest.java
  src/test/java/seedu/clinicio/model/medicine/MedicineQuantityTest.java
  src/test/java/seedu/clinicio/model/medicine/MedicineTest.java
  src/test/java/seedu/clinicio/model/medicine/MedicineTypeTest.java
  src/test/java/seedu/clinicio/model/medicine/UniqueMedicineListTest.java
  src/test/java/seedu/clinicio/storage/XmlAdaptedMedicineTest.java
  src/test/java/seedu/clinicio/testutil/ClinicIoBuilder.java
  src/test/java/seedu/clinicio/testutil/MedicineBuilder.java
  src/test/java/seedu/clinicio/testutil/TypicalPersons.java
Labels: PRStatus.ReadyForReview, charge.Model, charge.Storage, priority.High, type.Enhancement

#246 Implement Add patient command (III)
  docs/UserGuide.adoc
  src/main/java/seedu/clinicio/logic/commands/AddPatientCommand.java
  src/main/java/seedu/clinicio/logic/parser/CliSyntax.java
  src/main/java/seedu/clinicio/model/patient/Patient.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/clinicio/model/appointment/AppointmentTest.java
  src/test/java/seedu/clinicio/model/patient/PatientTest.java
Labels: PRStatus.WIP, charge.Logic, charge.Model, role.CodeQuality, role.Testing

#245 Add Queue Tab
  docs/team/iamjackslayer.adoc
  src/main/java/seedu/clinicio/MainApp.java
  src/main/java/seedu/clinicio/commons/events/ui/QueuePanelSelectionChangedEvent.java
  src/main/java/seedu/clinicio/logic/Logic.java
  src/main/java/seedu/clinicio/logic/LogicManager.java
  src/main/java/seedu/clinicio/logic/commands/AddApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/AddCommand.java
  src/main/java/seedu/clinicio/logic/commands/DequeueCommand.java
  src/main/java/seedu/clinicio/logic/commands/EnqueueCommand.java
  src/main/java/seedu/clinicio/logic/commands/FindCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListCommand.java
  src/main/java/seedu/clinicio/logic/commands/ShowPatientInQueueCommand.java
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/Model.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/ReadOnlyClinicIo.java
  src/main/java/seedu/clinicio/model/patientqueue/MainQueue.java
  src/main/java/seedu/clinicio/model/patientqueue/PreferenceQueue.java
  src/main/java/seedu/clinicio/model/patientqueue/UniqueQueue.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedPatient.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/java/seedu/clinicio/ui/QueuePanel.java
  src/main/java/seedu/clinicio/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QueueCard.fxml
  src/main/resources/view/QueuePanel.fxml
  src/test/java/seedu/clinicio/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AddCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/clinicio/model/ClinicIoTest.java
  src/test/java/seedu/clinicio/model/patientqueue/PreferenceQueueTest.java
Labels: PRStatus.ReadyForReview, charge.Model, charge.UI

#247 Improve test coverage for ClinicIO
  src/main/java/seedu/clinicio/ui/CommandBox.java
  src/main/java/seedu/clinicio/ui/util/PasswordPrefixFormatter.java
  src/test/java/seedu/clinicio/ui/util/PasswordPrefixFormatterTest.java
Labels: PRStatus.WIP, role.Testing

#227 Add functionality for multiple visualisations
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/analytics/Analytics.java
  src/main/java/seedu/clinicio/model/analytics/AppointmentStatistics.java
  src/main/java/seedu/clinicio/model/analytics/ChartType.java
  src/main/java/seedu/clinicio/model/analytics/DoctorStatistics.java
  src/main/java/seedu/clinicio/model/analytics/MedicineStatistics.java
  src/main/java/seedu/clinicio/model/analytics/PatientStatistics.java
  src/main/java/seedu/clinicio/model/analytics/Statistics.java
  src/main/java/seedu/clinicio/model/analytics/data/CircularList.java
  src/main/java/seedu/clinicio/model/analytics/data/StatData.java
  src/main/java/seedu/clinicio/model/analytics/data/SummaryData.java
  src/main/java/seedu/clinicio/model/analytics/data/Tuple.java
  src/main/java/seedu/clinicio/model/analytics/data/VisualizationData.java
  src/main/java/seedu/clinicio/model/analytics/util/DateUtil.java
  src/main/java/seedu/clinicio/model/analytics/util/TimeUtil.java
  src/main/java/seedu/clinicio/model/appointment/Date.java
  src/main/java/seedu/clinicio/model/appointment/Time.java
  src/main/java/seedu/clinicio/ui/BrowserPanel.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/java/seedu/clinicio/ui/analytics/AnalyticsDisplay.java
  src/main/java/seedu/clinicio/ui/analytics/Plot.java
  src/main/resources/view/Analytics.css
  src/main/resources/view/Analytics.fxml
  src/test/java/seedu/clinicio/model/ExportUtilTest.java
  src/test/java/seedu/clinicio/model/appointment/DateTest.java
Labels: PRStatus.ReadyForReview, charge.Model, charge.UI

#244 Add analytics tests
  src/test/java/seedu/clinicio/model/analytics/TimeUtilTest.java
Labels: PRStatus.ReadyForReview, role.Testing

#252 Require login for Medicine Commands
  src/main/java/seedu/clinicio/commons/core/Messages.java
  src/main/java/seedu/clinicio/logic/commands/AddMedicineCommand.java
  src/main/java/seedu/clinicio/logic/commands/AddPatientCommand.java
  src/main/java/seedu/clinicio/logic/commands/DeleteMedicineCommand.java
  src/main/java/seedu/clinicio/logic/commands/FindMedicineCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListMedicineCommand.java
  src/test/java/seedu/clinicio/logic/commands/AddMedicineCommandIntegrationTest.java
  src/test/java/seedu/clinicio/logic/commands/AddMedicineCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/DeleteMedicineCommandTest.java
Labels: PRStatus.ReadyForReview, charge.Logic, charge.UI, priority.High, type.Enhancement

#261 Implement List and Find Patient
  src/main/java/seedu/clinicio/commons/core/Messages.java
  src/main/java/seedu/clinicio/logic/commands/FindPatientCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListPatientCommand.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/logic/parser/FindPatientCommandParser.java
  src/main/java/seedu/clinicio/model/patient/PatientNameContainsKeywordsPredicate.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/FindPatientCommandTest.java
  src/test/java/seedu/clinicio/logic/parser/ClinicIoParserTest.java
  src/test/java/seedu/clinicio/logic/parser/FindPatientCommandParserTest.java
  src/test/java/seedu/clinicio/model/patient/PatientNameContainsKeywordsPredicateTest.java
Labels: PRStatus.ReadyForReview, charge.Logic

#262 Edit version v1.3 to v1.4
  src/main/java/seedu/clinicio/MainApp.java
Labels: PRStatus.ReadyForReview

#263 Edit user guide
  docs/UserGuide.adoc
Labels: PRStatus.WIP, role.Documentation

#241 Update PPP
  docs/team/jjlee050.adoc
Labels: PRStatus.WIP, role.Documentation

#240 Update DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: PRStatus.WIP, role.Documentation

#254 Refactor analytics ui
  src/main/java/seedu/clinicio/model/analytics/StatisticType.java
  src/main/java/seedu/clinicio/model/analytics/Statistics.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/java/seedu/clinicio/ui/analytics/AnalyticsDisplayPanel.java
  src/main/java/seedu/clinicio/ui/analytics/Plot.java
Labels: PRStatus.ReadyForReview, charge.UI

#265 Medicine UI
  src/main/java/seedu/clinicio/commons/events/ui/MedicinePanelSelectionChangedEvent.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/java/seedu/clinicio/ui/MedicineCard.java
  src/main/java/seedu/clinicio/ui/MedicineListPanel.java
  src/main/resources/images/medicines.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MedicineListCard.fxml
  src/main/resources/view/MedicineListPanel.fxml
  src/test/java/guitests/guihandles/MedicineCardHandle.java
  src/test/java/guitests/guihandles/MedicineListPanelHandle.java
  src/test/java/seedu/clinicio/ui/MedicineCardTest.java
  src/test/java/seedu/clinicio/ui/MedicineListPanelTest.java
  src/test/java/seedu/clinicio/ui/testutil/GuiTestAssert.java
Labels: PRStatus.WIP, charge.UI, priority.High, type.Enhancement

#260 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AnalyticsClassDiagram.png
  docs/images/AnalyticsScreenshot.png
  docs/images/ExportActivityDiagram.png
  docs/images/ExportSwimlaneDiagram.png
  docs/stylesheets/asciidoctor.css
  docs/team/arsalanc-v2.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#251 Edit ui
  README.adoc
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/java/seedu/clinicio/ui/PatientDetailsDisplayPanel.java
  src/main/java/seedu/clinicio/ui/PatientListPanel.java
  src/main/java/seedu/clinicio/ui/TitleScreen.java
  src/main/java/seedu/clinicio/ui/util/PasswordPrefixFormatter.java
  src/main/resources/images/allergy.png
  src/main/resources/images/clinicio_256.png
  src/main/resources/images/medicine.png
  src/main/resources/images/stethoscope.png
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientDetailsDisplayPanel.fxml
  src/main/resources/view/TitleScreen.fxml
Labels: PRStatus.WIP, charge.UI

#268 Tidy up UI
  src/main/java/seedu/clinicio/ui/AnalyticsDisplayPanel.java
  src/main/java/seedu/clinicio/ui/BrowserDisplayPanel.java
  src/main/java/seedu/clinicio/ui/CommandBox.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/java/seedu/clinicio/ui/PatientDetailsDisplayPanel.java
  src/main/java/seedu/clinicio/ui/Plot.java
  src/main/java/seedu/clinicio/ui/TitleScreen.java
  src/main/java/seedu/clinicio/ui/util/PasswordPrefixFormatter.java
  src/main/resources/view/AnalyticsDisplayPanel.fxml
  src/main/resources/view/BrowserDisplayPanel.fxml
  src/main/resources/view/PatientDetailsDisplayPanel.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/seedu/clinicio/ui/BrowserDisplayPanelTest.java
Labels: PRStatus.WIP, role.CodeQuality

#270 Update analytics
  src/main/java/seedu/clinicio/model/analytics/Analytics.java
  src/main/java/seedu/clinicio/model/analytics/PatientStatistics.java
  src/main/java/seedu/clinicio/model/analytics/Statistics.java
  src/main/java/seedu/clinicio/model/analytics/data/CircularList.java
  src/main/java/seedu/clinicio/model/analytics/data/StatData.java
  src/main/java/seedu/clinicio/model/analytics/util/DateUtil.java
  src/main/java/seedu/clinicio/ui/AnalyticsDisplayPanel.java
  src/main/java/seedu/clinicio/ui/Plot.java
  src/main/resources/view/Analytics.css
Labels: charge.Model

#271 Edit UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddApptSequenceDiagram.PNG
  docs/images/ApptClassDiagram.PNG
  docs/images/CancelApptSequenceDiagram.PNG
  docs/team/gingivitiss.adoc
  src/main/java/seedu/clinicio/ui/AppointmentDisplay.java
  src/main/resources/view/AppointmentDisplay.fxml
Labels: PRStatus.WIP, role.Documentation

#273 update consultation
  src/main/java/seedu/clinicio/storage/XmlAdaptedConsultation.java
Labels: charge.Storage

#275 Edit Medicine UI
  RepoSense.jar
  src/main/java/seedu/clinicio/logic/commands/AddMedicineCommand.java
  src/main/java/seedu/clinicio/model/medicine/MedicineName.java
  src/main/java/seedu/clinicio/model/medicine/MedicineType.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/java/seedu/clinicio/ui/MedicineCard.java
  src/main/java/seedu/clinicio/ui/MedicineDetailsDisplayPanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MedicineDetailsDisplayPanel.fxml
  src/main/resources/view/MedicineListCard.fxml
  src/test/java/guitests/guihandles/MedicineCardHandle.java
  src/test/java/seedu/clinicio/ui/testutil/GuiTestAssert.java
Labels: charge.UI, priority.High, type.Enhancement

#272 Tidy up Logic
  src/main/java/seedu/clinicio/logic/commands/LoginCommand.java
Labels: charge.Logic

#264 Edit developer guide
  docs/DeveloperGuide.adoc
  docs/images/LoginActivityDiagram.png
  docs/images/LoginClassDiagram.png
  docs/images/LoginCommonsSequenceDiagram.png
  docs/images/LoginLogicSequenceDiagram.png
  docs/images/LoginModelSequenceDiagram.png
  docs/images/LoginSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: PRStatus.ReadyForReview, role.Documentation

#256 Update logic class diagram
  docs/images/LogicClassDiagram.png
Labels: PRStatus.ReadyForReview, role.Documentation

#274 Appt ui
  src/main/java/seedu/clinicio/logic/commands/AddApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/CancelApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListAllApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListApptCommand.java
  src/main/java/seedu/clinicio/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/model/appointment/Appointment.java
  src/main/java/seedu/clinicio/model/appointment/Date.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/clinicio/ui/AppointmentDetailsDisplayPanel.java
  src/main/java/seedu/clinicio/ui/AppointmentDisplay.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/main/resources/view/AppointmentDetailsDisplayPanel.fxml
  src/main/resources/view/AppointmentDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/XmlSerializableClinicIoTest/typicalPersonsClinicIo.xml
  src/test/java/seedu/clinicio/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/CancelApptCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/ListAllApptTest.java
  src/test/java/seedu/clinicio/logic/commands/ListApptCommandTest.java
  src/test/java/seedu/clinicio/logic/parser/AddApptCommandParserTest.java
  src/test/java/seedu/clinicio/model/ClinicIoTest.java
  src/test/java/seedu/clinicio/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/clinicio/model/patient/PatientTest.java
  src/test/java/seedu/clinicio/testutil/TypicalPersons.java
Labels: PRStatus.WIP

#280 Add analytics tests
  src/main/java/seedu/clinicio/model/analytics/Analytics.java
  src/test/java/seedu/clinicio/model/analytics/AnalyticsIntegrationTest.java
Labels: role.Testing

#281 Add sample data.
  src/main/java/seedu/clinicio/model/util/SampleDataUtil.java
Labels: PRStatus.ReadyForReview

#278 Edit User guide.
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/user-guide-addpatient-after.png
  docs/images/user-guide-addpatient-before.png
  docs/images/user-guide-login-after.png
  docs/images/user-guide-login-before.png
  docs/images/user-guide-patient-management-ui.png
  docs/images/user-guide-ui-walkthrough-menu-bar.png
  docs/images/user-guide-ui-walkthrough-overview.png
  docs/images/user-guide-ui-walkthrough-tab-pane.png
Labels: PRStatus.WIP, role.Documentation

#283 Ugdg
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/images/ModelClassBetterOopDiagram.png
Labels: role.Documentation

#282 Edit developer guide
  docs/DeveloperGuide.adoc
  docs/images/FindPatientCommonsSequenceDiagram.png
  docs/images/FindPatientLogicSequenceDiagram.png
  docs/images/FindPatientModelSequenceDiagram.png
  docs/images/LoginLogicSequenceDiagram.png
  docs/images/user-guide-findpatient-after.png
  docs/images/user-guide-findpatient-before.png
  docs/images/user-guide-listpatient-after.png
  docs/images/user-guide-listpatient-before.png
Labels: PRStatus.ReadyForReview

#255 Add Switch Tab Event
  _reposense/config.json
  docs/team/iamjackslayer.adoc
  src/main/java/seedu/clinicio/MainApp.java
  src/main/java/seedu/clinicio/commons/events/ui/SwitchTabEvent.java
  src/main/java/seedu/clinicio/logic/LogicManager.java
  src/main/java/seedu/clinicio/logic/commands/AddApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/AddCommand.java
  src/main/java/seedu/clinicio/logic/commands/AddMedicineCommand.java
  src/main/java/seedu/clinicio/logic/commands/CancelApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/ChangeApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/DequeueCommand.java
  src/main/java/seedu/clinicio/logic/commands/EnqueueCommand.java
  src/main/java/seedu/clinicio/logic/commands/FindMedicineCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListMedicineCommand.java
  src/main/java/seedu/clinicio/logic/commands/ShowPatientInQueueCommand.java
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/Model.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/ui/MainWindow.java
  src/test/java/seedu/clinicio/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AddCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AddMedicineCommandTest.java
  src/test/java/seedu/clinicio/logic/commands/AddPatientCommandTest.java
Labels: PRStatus.ReadyForReview, priority.High

#286 Edit ui walkthrough for user guide.
  docs/UserGuide.adoc
  docs/images/user-guide-ui-walkthrough-tab-pane.png
Labels: PRStatus.ReadyForReview

#288 Fix broken links and images.
  docs/DeveloperGuide.adoc
Labels: role.Documentation

#291 fix userguide
  docs/UserGuide.adoc
Labels: PE Dry Run Bug, PRStatus.ReadyForReview, priority.High

#290 Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/addmed-command.png
  docs/images/after-deletemed-command.png
  docs/images/before-addmed-command.png
  docs/images/before-deletemed-command.png
  docs/images/listmed-command.png
  docs/team/aaronseahyh.adoc
Labels: role.Documentation

#289 add consultation storage
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/ReadOnlyClinicIo.java
  src/main/java/seedu/clinicio/storage/XmlSerializableClinicIo.java
  src/test/java/seedu/clinicio/model/ClinicIoTest.java
Labels: charge.Storage

#292 Listpatient
  src/main/java/seedu/clinicio/logic/commands/AddPatientCommand.java
  src/main/java/seedu/clinicio/logic/commands/DeleteMedicineCommand.java
  src/main/java/seedu/clinicio/logic/commands/FindPatientCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListAllApptCommand.java
  src/main/java/seedu/clinicio/logic/commands/ListPatientCommand.java
  src/main/resources/view/PatientListCard.fxml
Labels: PRStatus.ReadyForReview, charge.Logic, charge.UI, priority.High

#294 Edit ppp
  docs/team/gingivitiss.adoc
Labels: PRStatus.ReadyForReview, role.Documentation
