Repository CS2103-AY1819S1-W14-1/main, pull requests merged in 2018-10, with the labels that each got.

#74 Fix UI bug at main app launch
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: charge.UI, priority.High, role.CodeQuality, severity.High, type.Bug

#92 [UserGuide.adoc] Edit UserGuide to complement ClinicIO
  docs/UserGuide.adoc
Labels: priority.High, role.Documentation, severity.Medium, type.Bug

#94 Add login command into user guide.
  docs/UserGuide.adoc
Labels: priority.High, role.Documentation, type.Task

#93 Add login command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/doctor/Doctor.java
  src/main/java/seedu/address/model/doctor/Id.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/doctor/IdTest.java
  src/test/java/seedu/address/model/doctor/UniqueDoctorListTest.java
Labels: charge.Logic, charge.Model, priority.High, role.CodeQuality, role.Testing, type.Task

#102 fix command formatting in user guide
  docs/UserGuide.adoc
Labels: priority.High, role.Documentation, severity.Low, type.Bug

#109 README.adoc: Edit libraries used.
  README.adoc
Labels: role.Documentation

#108 Add login command
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/doctor/Password.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedDoctor.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/commons/util/HashUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/doctor/DoctorTest.java
  src/test/java/seedu/address/model/doctor/PasswordTest.java
  src/test/java/seedu/address/model/doctor/UniqueDoctorListTest.java
  src/test/java/seedu/address/storage/XmlAdapterDoctorTest.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: charge.Logic, charge.Model, role.CodeQuality, role.Testing, status.Ongoing

#105 Edit UI look and feel
  src/main/resources/fonts/OpenSans-Bold.ttf
  src/main/resources/fonts/OpenSans-BoldItalic.ttf
  src/main/resources/fonts/OpenSans-ExtraBold.ttf
  src/main/resources/fonts/OpenSans-ExtraBoldItalic.ttf
  src/main/resources/fonts/OpenSans-Italic.ttf
  src/main/resources/fonts/OpenSans-Light.ttf
  src/main/resources/fonts/OpenSans-LightItalic.ttf
  src/main/resources/fonts/OpenSans-Regular.ttf
  src/main/resources/fonts/OpenSans-SemiBold.ttf
  src/main/resources/fonts/OpenSans-SemiBoldItalic.ttf
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: charge.UI, status.Ongoing

#100 Add PreferenceQueue and MainQueue, both inherit from PatientQueue.
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PatientQueue.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/patientqueue/MainQueue.java
  src/main/java/seedu/address/model/patientqueue/PatientQueue.java
  src/main/java/seedu/address/model/patientqueue/PreferenceQueue.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/PatientQueueTest.java
  src/test/java/seedu/address/model/patientqueue/MainQueueTest.java
  src/test/java/seedu/address/model/patientqueue/PreferenceQueueTest.java
Labels: charge.Logic, charge.Model, role.CodeQuality, status.Ongoing

#116 remove product survey in developer guide [fix #103]
  docs/DeveloperGuide.adoc
Labels: PRStatus.ReadyForReview, priority.High, role.Documentation, severity.Low, type.Bug

#113 Add UniqueAppointmentList and CancelAppt
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/CancelApptCommand.java
  src/main/java/seedu/address/logic/commands/ChangeApptCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentClashException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: PRStatus.ReadyForReview, charge.Logic, charge.Model, role.CodeQuality, role.Testing

#120 Update user guide and developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: PRStatus.ReadyForReview, priority.High, role.Documentation

#118 DeveloperGuide.adoc: Add login authentication feature implementation
  docs/DeveloperGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#123 DeveloperGuide.adoc: Edit UI image.
  docs/images/Ui.png
Labels: PRStatus.ReadyForReview, role.Documentation, type.Task

#125 Edited UserGuide and DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation, type.Task

#114 Small edits to UserGuide and DevGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
Labels: PRStatus.WIP, charge.Model, role.Documentation

#112 Edit user guide
  docs/UserGuide.adoc
  docs/images/user-guide-help-window-after.png
Labels: PRStatus.ReadyForReview, role.Documentation

#119 Edit User guide/dev guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CancelApptSequenceDiagram.PNG
Labels: PRStatus.WIP, role.Documentation

#132 UserGuide.adoc: Edit user guide
  docs/UserGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#117 Add login command
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
Labels: PRStatus.WIP, charge.Logic, charge.UI, role.Testing

#135 Fix appointment equals
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/data/sandboxmanyPersons.xml
Labels: PRStatus.ReadyForReview, charge.Model, priority.High

#131 Add analytics support for appointments
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/analytics/Analytics.java
  src/main/java/seedu/address/model/analytics/Statistics.java
  src/main/java/seedu/address/model/analytics/TotalStatistics.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
Labels: PRStatus.ReadyForReview, charge.Model, priority.High, role.CodeQuality

#141 Update user guide and developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AnalyticsClassDiagram.png
Labels: PRStatus.ReadyForReview, priority.High, role.Documentation

#137 add consultation
  src/main/java/seedu/address/model/Consultation.java
Labels: PRStatus.ReadyForReview, charge.Model, priority.High, role.CodeQuality

#140 Edit developer guide
  docs/DeveloperGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#142 Add config.json
  _reposense/config.json
Labels: PRStatus.ReadyForReview, priority.High

#145 Move from v1.2 to v1.2.1
  src/main/java/seedu/address/MainApp.java
Labels: PRStatus.ReadyForReview, charge.UI

#127 Create Patient, inheriting from Person
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/sandboxmanyPersons.xml
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: PRStatus.ReadyForReview, charge.Model, priority.High, role.CodeQuality

#149 fix #148
  docs/images/AnalyticsClassDiagram.jpeg
Labels: PRStatus.ReadyForReview, role.Documentation, severity.Low, type.Bug

#126 PersonListPanelTest.java: Fix bug from SE-EDU AB Lvl 4 [Fix #110]
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: PRStatus.ReadyForReview, charge.UI, role.Testing

#143 Edit Queue-related Commands in User Guide
  docs/UserGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#147 Implementing Addappt
  src/main/java/seedu/clinicio/logic/commands/AddApptCommand.java
  src/main/java/seedu/clinicio/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/clinicio/logic/parser/CliSyntax.java
  src/main/java/seedu/clinicio/logic/parser/ParserUtil.java
  src/main/java/seedu/clinicio/model/appointment/Appointment.java
  src/main/java/seedu/clinicio/model/appointment/Date.java
  src/main/java/seedu/clinicio/model/appointment/Time.java
  src/main/java/seedu/clinicio/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedAppointment.java
  src/test/java/seedu/clinicio/logic/commands/CommandTestUtil.java
  src/test/java/seedu/clinicio/logic/parser/AddApptCommandParserTest.java
  src/test/java/seedu/clinicio/logic/parser/ParserUtilTest.java
  src/test/java/seedu/clinicio/model/ModelManagerTest.java
  src/test/java/seedu/clinicio/model/appointment/AppointmentTest.java
  src/test/java/seedu/clinicio/model/appointment/DateTest.java
  src/test/java/seedu/clinicio/model/appointment/TimeTest.java
  src/test/java/seedu/clinicio/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/clinicio/testutil/AppointmentBuilder.java
  src/test/java/seedu/clinicio/testutil/TypicalPersons.java
Labels: PRStatus.WIP, charge.Logic, charge.Model, role.CodeQuality, role.Testing

#152 Edit user guide
  docs/UserGuide.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#151 Update DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
  docs/images/LoginActivityDiagram.png
  docs/images/LoginSequenceDiagram.png
Labels: PRStatus.ReadyForReview, role.Documentation

#156 Make export functional
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AnalyticsClassDiagram.jpeg
  docs/images/ExportActivityDiagram.png
  src/main/java/seedu/clinicio/logic/commands/ExportPatientsAppointmentsCommand.java
  src/main/java/seedu/clinicio/logic/commands/ExportPatientsCommand.java
  src/main/java/seedu/clinicio/logic/commands/ExportPatientsConsultationsCommand.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/model/ExportPatientsData.java
  src/main/java/seedu/clinicio/model/Model.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/consultation/Consultation.java
  src/main/java/seedu/clinicio/model/consultation/exceptions/NonDoctorException.java
  src/main/java/seedu/clinicio/model/patient/Patient.java
  src/main/java/seedu/clinicio/model/util/ExportUtil.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedConsultation.java
  src/test/java/seedu/clinicio/logic/commands/AddCommandTest.java
Labels: PRStatus.ReadyForReview, charge.Logic, charge.Model, priority.High, role.CodeQuality, role.Documentation

#163 Move ClinicIO to 1.3
  _reposense/config.json
  src/main/java/seedu/clinicio/MainApp.java
Labels: PRStatus.ReadyForReview

#157 Edit config.json
  _reposense/config.json
Labels: PRStatus.ReadyForReview

#162 Fix addappt
  .gitignore
  docs/UserGuide.adoc
  docs/team/gingivitiss.adoc
  src/main/java/seedu/clinicio/logic/commands/AddApptCommand.java
  src/main/java/seedu/clinicio/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/clinicio/logic/parser/AddCommandParser.java
  src/main/java/seedu/clinicio/logic/parser/CliSyntax.java
  src/main/java/seedu/clinicio/logic/parser/ClinicIoParser.java
  src/main/java/seedu/clinicio/logic/parser/ParserUtil.java
  src/main/java/seedu/clinicio/model/ClinicIo.java
  src/main/java/seedu/clinicio/model/ModelManager.java
  src/main/java/seedu/clinicio/model/appointment/Appointment.java
  src/main/java/seedu/clinicio/storage/XmlAdaptedAppointment.java
  src/test/java/seedu/clinicio/logic/commands/CommandTestUtil.java
  src/test/java/seedu/clinicio/logic/parser/AddApptCommandParserTest.java
  src/test/java/seedu/clinicio/model/ModelManagerTest.java
  src/test/java/seedu/clinicio/model/appointment/AppointmentTest.java
  src/test/java/seedu/clinicio/model/password/PasswordTest.java~HEAD
  src/test/java/seedu/clinicio/model/staff/StaffTest.java~HEAD
  src/test/java/seedu/clinicio/model/staff/StaffTest.java~upstream_master
  src/test/java/seedu/clinicio/testutil/AppointmentBuilder.java
  src/test/java/seedu/clinicio/testutil/TypicalPersons.java
Labels: PRStatus.ReadyForReview, charge.Logic, charge.Model

#171 update reposense config
  _reposense/config.json
Labels: PRStatus.ReadyForReview, priority.High

#168 Update AboutUs.adoc
  docs/AboutUs.adoc
Labels: PRStatus.ReadyForReview, role.Documentation

#144 Edit color when hover over the card in PersonList.
  src/main/resources/view/LightTheme.css
Labels: PRStatus.ReadyForReview, charge.UI
