Repository CS2103-AY1819S1-W14-1/main, pull requests merged in 2018-09, with the labels that each got.

#14 Reupload about us image.
  docs/images/jjlee050.jpg
Labels: Priority: High, Type: Task

#17 update AboutUs with Arsalan's profile
  docs/AboutUs.adoc
  docs/images/arsalanc-v2.png
  docs/team/arsalanc-v2.adoc
Labels: Priority: High, Type: Task

#21 Edit intro in UserGuide.adoc
  docs/UserGuide.adoc
Labels: Priority: High, Type: Task

#22 Update README document
  README.adoc
  docs/LearningOutcomes.adoc
  docs/images/Ui.png
  docs/images/jjlee050.jpg
Labels: Priority: High, Type: Task

#24 ContactUs.adoc: Edit contact us page description
  docs/ContactUs.adoc
Labels: Priority: High, Type: Task

#20 update Appendix in developer guide
  docs/DeveloperGuide.adoc
Labels: Priority: High, Status: Ongoing, Type: Task

#27 Update AboutUs.adoc
  docs/AboutUs.adoc
Labels: Priority: High, Type: Task

#43 Reupload profile image and edit build gradle
  build.gradle
  docs/images/jjlee050.png
Labels: priority.High, type.Task

#47 AboutUs.adoc: Remove dummy user
  docs/AboutUs.adoc
Labels: priority.High, type.Task

#52 Change team name and date of changes for User and Developer Guide.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#53 Minor UI Refinements
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: priority.Medium, type.Task

#61 update appendix C in developer guide
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#60 Update Developer Guide
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Bug, type.Task

#62 docs/DeveloperGuide: Fix hidden appendices
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Bug

#63 Add Doctor Model, accept Doctor in the file and set up password hashing.
  build.gradle
  src/main/java/seedu/address/commons/util/HashUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/doctor/Doctor.java
  src/main/java/seedu/address/model/doctor/Id.java
  src/main/java/seedu/address/model/doctor/Password.java
  src/main/java/seedu/address/model/doctor/UniqueDoctorList.java
  src/main/java/seedu/address/model/doctor/exceptions/DoctorNotFoundException.java
  src/main/java/seedu/address/model/doctor/exceptions/DuplicateDoctorException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedDoctor.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/commons/util/HashUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
  src/test/java/seedu/address/model/doctor/DoctorTest.java
  src/test/java/seedu/address/model/doctor/IdTest.java
  src/test/java/seedu/address/model/doctor/PasswordTest.java
  src/test/java/seedu/address/model/doctor/UniqueDoctorListTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: charge.Model, charge.Storage, priority.High, role.CodeQuality, role.Testing, type.Task

#51 Create queue
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PatientQueue.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/PatientQueueTest.java
Labels: charge.Model, priority.High, status.Ongoing

#75 AbousUs.adoc: Edit roles and responsibilities.
  docs/AboutUs.adoc
Labels: role.Documentation, type.Task

#78 AboutUs.adoc: Edit incorrect format
  docs/AboutUs.adoc
Labels: role.Documentation, severity.Low, type.Bug

#77 fix typo in developer guide
  docs/DeveloperGuide.adoc
Labels: role.Documentation, severity.Low, type.Bug
